[book]
title = "智能涌动"
authors = ["新褶"]
language = "zh"
multilingual = false
src = "src"

[build]
build-dir = "book-output"

[output.html]
default-theme = "navy"
git-repository-url = "https://github.com/leether/ai-saga-book"
edit-url-template = "https://github.com/leether/ai-saga-book/edit/main/book/src/{path}"
additional-css = ["theme/custom.css"]

[output.html.print]
enable = true
